- hosts: generic
  remote_user: pi
  vars:
    nodeVersion: node-v4.0.0-linux-armv6l
  tasks:

  - name: Update apt
    become: yes
    apt: update_cache=yes

  - name: Update packages
    become: yes
    apt: upgrade=yes

  - name: remove unnecessary stuff
    become: yes
    apt: name={{ item }} state=absent purge=yes
    with_items:
      - wolfram-engine

  - name: install tools
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - mc
      - git-core
      - nano
      - screen
      - apt-transport-https
      - daemon

  - name: get node tarball
    become: yes
    unarchive: src="https://nodejs.org/dist/v4.0.0/{{nodeVersion}}.tar.gz" dest="/usr/local/" copy=no creates="/usr/local/bin/node"

  - name: link node
    become: yes
    file: src=/usr/local/{{nodeVersion}}/bin/node dest=/usr/local/bin/node state=link

  - name: link npm
    become: yes
    file: src=/usr/local/{{nodeVersion}}/bin/npm dest=/usr/local/bin/npm state=link

  - name: clone git repo
    git: repo=git://github.com/JustgeekDE/humidityLogger.git dest=/home/pi/humidityLogger

  - name: install node modules
    command: npm install chdir=/home/pi/humidityLogger/backend

  - name: start backend
    shell: daemon -- node index.js chdir=/home/pi/humidityLogger/backend
